import  {createApp } from 'vue'
import 'primeflex/primeflex.css';
import './style.css'
import App from './App.vue'
import PrimeVue from 'primevue/config';
import  Accordion  from 'primevue/accordion';
import  AutoComplete  from 'primevue/autocomplete';
import  Avatar  from 'primevue/avatar';
import  Badge  from 'primevue/badge';
import  BlockUI  from 'primevue/blockui';
import  Breadcrumb  from 'primevue/breadcrumb';
import  Button  from 'primevue/button';
import  Card  from 'primevue/card';
import ConfirmDialog  from 'primevue/confirmdialog';
import  ConfirmPopup  from 'primevue/confirmpopup';
import  DataView  from 'primevue/dataview';
import  DataTable  from 'primevue/datatable';
import  DataViewLayoutOptions  from 'primevue/dataviewlayoutoptions';
import  DeferredContent  from 'primevue/deferredcontent';
import  Dialog  from 'primevue/dialog';
import Divider  from 'primevue/divider';
import  Dropdown  from 'primevue/dropdown';
import  Fieldset  from 'primevue/fieldset';
import  FileUpload  from 'primevue/fileupload';
import  Galleria  from 'primevue/galleria';
import  Inplace  from 'primevue/inplace';
import InputMask  from 'primevue/inputmask';
import  InputNumber  from 'primevue/inputnumber';
import  InputSwitch  from 'primevue/inputswitch';
import  InputText  from 'primevue/inputtext';
import Knob  from 'primevue/knob';
import  Menu  from 'primevue/menu';
import  Menubar  from 'primevue/menubar';
import  Message  from 'primevue/message';
import  MultiSelect  from 'primevue/multiselect';
import  OrderList  from 'primevue/orderlist';
import  OrganizationChart  from 'primevue/organizationchart';
import  OverlayPanel  from 'primevue/overlaypanel';
import  Paginator  from 'primevue/paginator';
import  Panel  from 'primevue/panel';
import  PanelMenu  from 'primevue/panelmenu';
import  Password  from 'primevue/password';
import  PickList  from 'primevue/picklist';
import  ProgressBar  from 'primevue/progressbar';
import  ProgressSpinner  from 'primevue/progressspinner';
import  RadioButton  from 'primevue/radiobutton';
import  Rating  from 'primevue/rating';
import  Ripple  from 'primevue/ripple';
import  Row  from 'primevue/row';
import  ScrollPanel  from 'primevue/scrollpanel';
import  SelectButton  from 'primevue/selectbutton';
import  Sidebar  from 'primevue/sidebar';
import Slider  from 'primevue/slider';
import  SplitButton  from 'primevue/splitbutton';
import  Splitter  from 'primevue/splitter';
import  SplitterPanel  from 'primevue/splitterpanel';
import Steps from 'primevue/steps';
import  TabMenu  from 'primevue/tabmenu';
import  TabPanel  from 'primevue/tabview';
import  Tag  from 'primevue/tag';
import  Terminal  from 'primevue/terminal';
import  Textarea  from 'primevue/textarea';
import  TieredMenu  from 'primevue/tieredmenu';
import  Timeline  from 'primevue/timeline';
import  Toast  from 'primevue/toast';
import  ToastService  from 'primevue/toastservice';
import  ToggleButton  from 'primevue/togglebutton';
import  Toolbar  from 'primevue/toolbar';
import  Tooltip  from 'primevue/tooltip';
import  Tree  from 'primevue/tree';
import  TreeSelect  from 'primevue/treeselect';
import  TriStateCheckbox  from 'primevue/tristatecheckbox';

import 'primevue/resources/themes/bootstrap4-light-blue/theme.css';
import 'primevue/resources/primevue.min.css';
import 'primeicons/primeicons.css';      

const app = createApp(App)
app.use(PrimeVue);
app.component('Accordion', Accordion);
app.component('AutoComplete', AutoComplete);
app.component('Avatar', Avatar);
app.component('Badge', Badge);
app.component('BlockUI', BlockUI);
app.component('Breadcrumb', Breadcrumb);
app.component('Button', Button);
app.component('Card', Card);
app.component('ConfirmDialog', ConfirmDialog);
app.component('ConfirmPopup', ConfirmPopup);
app.component('DataView', DataView);
app.component('DataTable', DataTable);
app.component('DataViewLayoutOptions', DataViewLayoutOptions);
app.component('DeferredContent', DeferredContent);
app.component('Dialog', Dialog);
app.component('Divider', Divider);
app.component('Dropdown', Dropdown);
app.component('Fieldset', Fieldset);
app.component('FileUpload', FileUpload);
app.component('Galleria', Galleria);
app.component('Inplace', Inplace);
app.component('InputMask', InputMask);
app.component('InputNumber', InputNumber);
app.component('InputSwitch', InputSwitch);
app.component('InputText', InputText);
app.component('Knob', Knob);
app.component('Menu', Menu);
app.component('Menubar', Menubar);
app.component('Message', Message);
app.component('MultiSelect', MultiSelect);
app.component('OrderList', OrderList);
app.component('OrganizationChart', OrganizationChart);
app.component('OverlayPanel', OverlayPanel);
app.component('Paginator', Paginator);
app.component('Panel', Panel);
app.component('PanelMenu', PanelMenu);
app.component('Password', Password);
app.component('PickList', PickList);
app.component('ProgressBar', ProgressBar);
app.component('ProgressSpinner', ProgressSpinner);
app.component('RadioButton', RadioButton);
app.component('Rating', Rating);
app.component('Ripple', Ripple);
app.component('Row', Row);
app.component('ScrollPanel', ScrollPanel);
app.component('SelectButton', SelectButton);
app.component('Sidebar', Sidebar);
app.component('Slider', Slider);
app.component('SplitButton', SplitButton);
app.component('Splitter', Splitter);
app.component('SplitterPanel', SplitterPanel);
app.component('Steps', Steps);
app.component('TabMenu', TabMenu);
app.component('TabPanel', TabPanel);
app.component('Tag', Tag);
app.component('Terminal', Terminal);
app.component('Textarea', Textarea);
app.component('TieredMenu', TieredMenu);
app.component('Timeline', Timeline);
app.component('Toast', Toast);
app.component('ToastService', ToastService);
app.component('ToggleButton', ToggleButton);
app.component('Toolbar', Toolbar);
app.component('Tooltip', Tooltip);
app.component('Tree', Tree);
app.component('TreeSelect', TreeSelect);
app.component('TriStateCheckbox', TriStateCheckbox);


app.mount('#app')


